### ISSUE TITLE
google-maps-api

### ISSUE THREAD

**Issue by kmuali** [kmuali/BusMate#12]
Using Javascript and html, create a page which contains only Map frame. 

The frame lets user to select nodes and connect them, i.e. create a route or a path. 

Output is a json in browser's console.

Do not make any styling, nor GPS locator, just create functional html frame with console output.

Put Javascript file(s) in static/js/ and html in templates/.

**Comment by ankit-pn** [comment]
Hey @kmuali , I want to work on this issue, it would be great if you assign this issue to me.
Thanks

**Comment by kmuali** [comment]
@ankit-pn, you are now assigned
